version: "3"
services:
  neo4j:
    image: neo4j
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      # Same as in `functions/.env` file (don't change).
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["graph-data-science", "apoc","n10s"]
    volumes:
      - neo4j-db-volume:/data/target/neo4j/data
      - ./neo4j_files/plugins:/data/target/neo4j/plugins
    networks:
      - biopipeline
  bioetlpipeline:
    environment:
      - NEO4J_URL=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test1234
    build: .
    depends_on: [neo4j]
    ports:
      - 8501:8501
    networks:
        - biopipeline
    tty: true
volumes:
  neo4j-db-volume:
networks:
    biopipeline:
      driver: bridge